// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	message.proto
	service.proto

It has these top-level messages:
	Envelope
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MessageType int32

const (
	MessageType_HEARTBEAT MessageType = 0
)

var MessageType_name = map[int32]string{
	0: "HEARTBEAT",
}
var MessageType_value = map[string]int32{
	"HEARTBEAT": 0,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}
func (MessageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Envelope struct {
	Sender    string      `protobuf:"bytes,1,opt,name=sender" json:"sender,omitempty"`
	Timestamp string      `protobuf:"bytes,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Type      MessageType `protobuf:"varint,3,opt,name=type,enum=pb.MessageType" json:"type,omitempty"`
	Message   []byte      `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
}

func (m *Envelope) Reset()                    { *m = Envelope{} }
func (m *Envelope) String() string            { return proto.CompactTextString(m) }
func (*Envelope) ProtoMessage()               {}
func (*Envelope) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Envelope) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *Envelope) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *Envelope) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_HEARTBEAT
}

func (m *Envelope) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func init() {
	proto.RegisterType((*Envelope)(nil), "pb.Envelope")
	proto.RegisterEnum("pb.MessageType", MessageType_name, MessageType_value)
}

func init() { proto.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 164 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0xaa, 0xe7,
	0xe2, 0x70, 0xcd, 0x2b, 0x4b, 0xcd, 0xc9, 0x2f, 0x48, 0x15, 0x12, 0xe3, 0x62, 0x2b, 0x4e, 0xcd,
	0x4b, 0x49, 0x2d, 0x92, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf2, 0x84, 0x64, 0xb8, 0x38,
	0x4b, 0x32, 0x73, 0x53, 0x8b, 0x4b, 0x12, 0x73, 0x0b, 0x24, 0x98, 0xc0, 0x52, 0x08, 0x01, 0x21,
	0x65, 0x2e, 0x96, 0x92, 0xca, 0x82, 0x54, 0x09, 0x66, 0x05, 0x46, 0x0d, 0x3e, 0x23, 0x7e, 0xbd,
	0x82, 0x24, 0x3d, 0x5f, 0x88, 0x35, 0x21, 0x95, 0x05, 0xa9, 0x41, 0x60, 0x49, 0x21, 0x09, 0x2e,
	0x76, 0xa8, 0xdd, 0x12, 0x2c, 0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x30, 0xae, 0x96, 0x0c, 0x17, 0x37,
	0x92, 0x72, 0x21, 0x5e, 0x2e, 0x4e, 0x0f, 0x57, 0xc7, 0xa0, 0x10, 0x27, 0x57, 0xc7, 0x10, 0x01,
	0x86, 0x24, 0x36, 0xb0, 0x4b, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x8f, 0x3d, 0x48, 0xf5,
	0xba, 0x00, 0x00, 0x00,
}
